apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sserkanguzel/your-gitops-repo.git
    targetRevision: main
    path: manifests/hive-metastore
  destination:
    server: https://kubernetes.default.svc
    namespace: hive-metastore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
