image:
  repository: hashicorp/vault
  tag: 1.15.5

service:
  type: ClusterIP
  port: 8200

ui:
  enabled: true
  serviceType: NodePort
  nodePort: 30820

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""