apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog-lake
data:
  lake.properties: |
    connector.name=hive
    hive.metastore=filesystem
    hive.s3.catalog-directory=s3a://testbuckettrino/testpathtrino/
    hive.s3.aws-access-key=minioadmin
    hive.s3.aws-secret-key=minioadmin
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
