apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog-ice
data:
  ice.properties: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.hive-metastore.svc.cluster.local:9083
    warehouse=s3a://testbuckettrino/testpathtrino
    
    hive.s3.aws-access-key=minioadmin
    hive.s3.aws-secret-key=minioadmin
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
