apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog-ice
data:
  ice.properties: |
    connector.name=iceberg
    catalog.type=filesystem
    warehouse=s3a://{{ .Values.trino.iceberg.bucket }}/{{ .Values.trino.iceberg.path }}
    hive.s3.aws-access-key={{ .Values.trino.iceberg.accessKey }}
    hive.s3.aws-secret-key={{ .Values.trino.iceberg.secretKey }}
    hive.s3.endpoint={{ .Values.trino.iceberg.endpoint }}
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
