apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog-lake
data:
  lake.properties: |
    connector.name=iceberg
    catalog.type=filesystem
    warehouse=s3a://testbuckettrino/testpathtrino  # change to your bucket

    hive.s3.aws-access-key=minioadmin
    hive.s3.aws-secret-key=minioadmin
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
