apiVersion: v1
kind: Service
metadata:
  name: trino
spec:
  type: {{ .Values.trino.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.trino.service.nodePort }}
  selector:
    app: trino
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      volumes:
        - name: trino-catalog
          emptyDir: {}  # temp volume shared between initContainer and main container

      initContainers:
        - name: catalog-init
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Writing iceberg catalog..."
              mkdir -p /catalog
              cat <<EOF > /catalog/ice.properties
              connector.name=iceberg
              catalog.type=filesystem
              warehouse=s3a://testbuckettrino/testpathtrino
              hive.s3.aws-access-key=minioadmin
              hive.s3.aws-secret-key=minioadmin
              hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
              hive.s3.path-style-access=true
              hive.s3.ssl.enabled=false
              EOF
          volumeMounts:
            - name: trino-catalog
              mountPath: /catalog

      containers:
        - name: trino
          image: trinodb/trino:422
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-catalog
              mountPath: /etc/trino/catalog
