apiVersion: v1
kind: Service
metadata:
  name: trino
spec:
  type: {{ .Values.trino.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.trino.service.nodePort }}
  selector:
    app: trino
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
        - name: trino
          image: "{{ .Values.trino.image.repository }}:{{ .Values.trino.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: catalog
              mountPath: /etc/trino/catalog
      volumes:
        - name: catalog
          configMap:
            name: trino-catalog-ice
