apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: trino
spec:
  type: {{ .Values.trino.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.trino.service.nodePort }}
  selector:
    app: trino
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      volumes:
        - name: trino-catalog
          configMap:
            name: trino-catalog-ice
        - name: trino-lib-extra
          emptyDir: {}

      initContainers:
        - name: fetch-hadoop-s3a-jars
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /jars && cd /jars
              echo "Downloading Hadoop AWS and SDK jars..."
              curl -LO https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar
              curl -LO https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
          volumeMounts:
            - name: trino-lib-extra
              mountPath: /jars

      containers:
        - name: trino
          image: "{{ .Values.trino.image.repository }}:{{ .Values.trino.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: TRINO_EXTRA_CLASSPATH
              value: /usr/lib/trino/lib-extra/*
          volumeMounts:
            - name: trino-catalog
              mountPath: /etc/trino/catalog
            - name: trino-lib-extra
              mountPath: /usr/lib/trino/lib-extra


