apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-postgresql-config
  namespace: postgresql
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::/0                    md5
