executor: KubernetesExecutor

airflow:
  image:
    repository: apache/airflow
    tag: 2.9.0

  config:
    AIRFLOW__CORE__FERNET_KEY: "aHnmZvJEV_3AGCK75H-lhBdcdhJCtRXC61tr9KyP6HM="
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"

  defaultUser:
    enabled: true
    username: admin
    password: admin

dags:
  gitSync:
    enabled: true
    repo: https://github.com/sserkanguzel/Project-1-Batch-Processing.git
    branch: main
    subPath: dags
    interval: 60
    depth: 1
    wait: 5
    credentialsSecret: ""  # Leave blank for public repo
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi

webserver:
  service:
    type: NodePort
    port: 8080

postgresql:
  enabled: true
  persistence:
    enabled: true
    storageClass: local-path
    size: 8Gi

logs:
  persistence:
    enabled: true
    storageClass: local-path
    size: 1Gi

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
  
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
