executor: KubernetesExecutor

airflow:
  image:
    repository: apache/airflow
    tag: 2.9.1
    pullPolicy: IfNotPresent
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

  config:
    AIRFLOW__CORE__FERNET_KEY: "your-fernet-key"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"

  dags:
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteMany
      size: 1Gi
    gitSync:
      enabled: true
      repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git
      branch: main
      subPath: dags
      syncWait: 60
      depth: 1

  logs:
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteMany
      size: 1Gi

  persistence:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi

webserver:
  defaultUser:
    enabled: false  # already defined above
  service:
    type: NodePort
    port: 8080

scheduler:
  replicas: 1

workers:
  enabled: true
  replicas: 1

triggerer:
  enabled: true
  replicas: 1

flower:
  enabled: true
  service:
    type: ClusterIP

redis:
  enabled: true

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

ingress:
  enabled: false
