airflowVersion: "2.9.1"

executor: KubernetesExecutor

airflow:
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

webserver:
  enabled: true
  port: 8080
  service:
    type: NodePort
    nodePort: 30080  # Optional: choose a specific port or remove to auto-assign
  persistence:
    enabled: false
  waitForMigrations: # Ensure Airflow starts only after DB schema is up-to-date. 
    enabled: false
    securityContexts:
      container: {} 
  podDisruptionBudget: # How many pods of a particular application can be down at the same time during voluntary disruptions
    enabled: false
  livenessProbe: # Kubernetes mechanism to check if a pod is healthy
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    scheme: HTTP
    path: /health
    port: 8080
  readinessProbe: # Tells Kubernetes when the pod is ready to accept traffic.
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    scheme: HTTP
    path: /health
    port: 8080
  startupProbe: # Checks if the app inside the pod has started properly
    enabled: true
    failureThreshold: 30
    periodSeconds: 10
    timeoutSeconds: 5
    scheme: HTTP
    path: /health
    port: 8080
  securityContexts:
    pod: {}
    container: {}
  serviceAccount: ## Service Account: In Kubernetes, a ServiceAccount provides an identity for pods to interact with the Kubernetes API
    create: true
  hpa: ## hpa: Horizontal Pod AutoScaler
    enabled: false
  
config:
  webserver:
    base_url: "http://localhost:8080"
  core:
    dags_folder: "/opt/airflow/dags"
    load_examples: "False"

scheduler:
  enabled: true

triggerer:
  enabled: true
  replicas: 1
  keda:
    enabled: false
  serviceAccount:
    create: true
  securityContexts:
    pod: {}
    container: {}
  persistence:
    enabled: false

workers:
  keda:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
  persistence:
    enabled: false
  serviceAccount:
    create: true
  hpa:
    enabled: false
    
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/sserkanguzel/your-dag-repo.git
    branch: main
    subPath: dags   # adjust if your DAGs are in a subfolder
    depth: 1
    syncInterval: 60
    credentials:
      username: ""   # Leave blank if public repo
      password: ""   # Or use `existingSecret` if private

logs:
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 8Gi

data:
  metadataConnection:
    protocol: "postgresql"
    user: "airflow"
    pass: "airflow"
    host: "postgresql"
    port: 5432
    database: "airflow"
    query: "sslmode=disable"

redis:
  enabled: true

ingress:
  enabled: false  # We're using NodePort instead
  web:
    enabled: false
namespace: airflow

ports:
  pgbouncer: 6432

images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

enableBuiltInSecretEnvVars:
  AIRFLOW__CORE__FERNET_KEY: true
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: true
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: true
  AIRFLOW_CONN_AIRFLOW_DB: true
  AIRFLOW__API_AUTH__JWT_SECRET: true
  AIRFLOW__WEBSERVER__SECRET_KEY: true
  AIRFLOW__CELERY__CELERY_RESULT_BACKEND: true
  AIRFLOW__CELERY__RESULT_BACKEND: true
  AIRFLOW__CELERY__BROKER_URL: true
  AIRFLOW__ELASTICSEARCH__HOST: true
  AIRFLOW__ELASTICSEARCH__ELASTICSEARCH_HOST: true
  AIRFLOW__OPENSEARCH__HOST: true
  
securityContexts: ## Security Context: Filesystem access, UID ID access etc configurations
  pod: {}
  container: {}
networkPolicies: 
  enabled: false
pgbouncer: # ## Security Context: Filesystem access, UID ID access etc configurations
  enabled: false
kerberos: ## Airflow can optionally integrate with Kerberos for secure user authentication.
  enabled: false
registry: ## Used if pulling airflow images from a private registry
  secretName: ""
elasticsearch:
  enabled: false
opensearch:
  enabled: false
