airflowVersion: "2.9.1"

executor: KubernetesExecutor

airflow:
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

webserver:
  enabled: true
  port: 8080
  service:
    type: NodePort
    nodePort: 30080  # Optional: choose a specific port or remove to auto-assign
  persistence:
    enabled: false
  waitForMigrations: # Ensure Airflow starts only after DB schema is up-to-date. 
    enabled: false
    securityContexts:
      container: {} 
  podDisruptionBudget:
    enabled: false  
  securityContexts:
    pod: {}
    container: {}
  serviceAccount: ## Service Account: In Kubernetes, a ServiceAccount provides an identity for pods to interact with the Kubernetes API
    create: true
  hpa: ## hpa: Horizontal Pod AutoScaler
    enabled: false
  
config:
  core:
    dags_folder: "/opt/airflow/dags"
    load_examples: "False"

scheduler:
  enabled: true

triggerer:
  enabled: true

workers:
  keda:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
  persistence:
    enabled: false
  
  serviceAccount:
    create: true
  hpa:
    enabled: false
    
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/sserkanguzel/your-dag-repo.git
    branch: main
    subPath: dags   # adjust if your DAGs are in a subfolder
    depth: 1
    syncInterval: 60
    credentials:
      username: ""   # Leave blank if public repo
      password: ""   # Or use `existingSecret` if private

logs:
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 8Gi

data:
  metadataConnection:
    protocol: "postgresql"
    user: "airflow"
    pass: "airflow"
    host: "postgresql"
    port: 5432
    database: "airflow"
    query: "sslmode=disable"


redis:
  enabled: true

ingress:
  enabled: false  # We're using NodePort instead
  web:
    enabled: false
namespace: airflow

ports:
  pgbouncer: 6432

images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
  
securityContexts: ## Security Context: Filesystem access, UID ID access etc configurations
  pod: {}
  container: {}
networkPolicies: 
  enabled: false
pgbouncer: # ## Security Context: Filesystem access, UID ID access etc configurations
  enabled: false
kerberos: ## Airflow can optionally integrate with Kerberos for secure user authentication.
  enabled: false
registry: ## Used if pulling airflow images from a private registry
  secretName: ""
