executor: LocalExecutor

airflow:
  image:
    repository: apache/airflow
    tag: 2.9.1
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  defaultUser:
    enabled: true
    username: admin
    password: admin
  extraEnv:
    - name: AIRFLOW__CORE__FERNET_KEY
      value: "CuBp2CJekK8O4UA89QI_AxcR1mEET-9eIy4bO250quA="  # Use a real key in practice

webserver:
  service:
    type: ClusterIP
    port: 8080

logs:
  persistence:
    enabled: false

redis:
  enabled: true

postgresql:
  enabled: true
  auth:
    postgresPassword: airflowpass
    username: airflow
    password: airflowpass
    database: airflow
