executor: KubernetesExecutor

airflow:
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com

web:
  enabled: true
  port: 8080
  service:
    type: NodePort
    nodePort: 30080  # Optional: choose a specific port or remove to auto-assign

scheduler:
  enabled: true

triggerer:
  enabled: true

workers:
  serviceAccount:
    create: true

  keda:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300

  persistence:
    enabled: false

  hpa:
    enabled: false
    
dags:
  gitSync:
    enabled: true
    repo: https://github.com/sserkanguzel/your-dag-repo.git
    branch: main
    subPath: dags   # adjust if your DAGs are in a subfolder
    depth: 1
    syncInterval: 60
    credentials:
      username: ""   # Leave blank if public repo
      password: ""   # Or use `existingSecret` if private

logs:
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 8Gi

redis:
  enabled: true

ingress:
  enabled: false  # We're using NodePort instead

namespace: airflow

images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

networkPolicies:
  enabled: false
