# kubernetes/airflow/config/airflow-pod-template-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-pod-template # This must match the ConfigMap name in scheduler.yaml
  namespace: airflow # Resolved from {{ .Values.namespace }}
data:
  # The key 'pod_template.yaml' must match the 'path' in the volumeMounts in scheduler.yaml
  # The value is the *entire content* of the pod_template.yaml file, properly indented.
  pod_template.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-name
    spec:
      restartPolicy: Never
      serviceAccountName: airflow
      shareProcessNamespace: false
      initContainers:
        - name: git-sync
          image: "k8s.gcr.io/git-sync/git-sync:v3.6.9"
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/sserkanguzel/Project-1-Batch-Processing.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_SUBPATH
              value: "dags"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
          volumeMounts:
            - name: dags-volume
              mountPath: /git
      containers:
        - name: base
          image: "apache/airflow:2.7.1-python3.9"
          imagePullPolicy: IfNotPresent
          command: ["/entrypoint.sh"] # CRITICAL FIX
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: "/opt/airflow/dags/repo/dags"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflowpassword@postgres-postgresql.airflow.svc.cluster.local:5432/airflow_db
            - name: AIRFLOW__CORE__FERNET_KEY
              value: "bXKd_nJ7Yj0E309u7oh-cmXcFC89gi1IllSBl21Ku5g="
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: "Td_-CejX_6foYTgUzLXfrgVWvxlAuzp4Cemjf6J57b0"
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "20"
          ports: []
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
              readOnly: true
      volumes:
        - name: dags-volume
          emptyDir: {}
