apiVersion: v1
kind: Pod
metadata:
  name: git-sync
  namespace: {{ .Values.namespace }}
  labels:
    app: git-sync
spec:
  restartPolicy: Always
  containers:
    - name: git-sync
      image: "{{ .Values.gitSync.image.repository }}:{{ .Values.gitSync.image.tag }}"
      env:
        - name: GIT_SYNC_REPO
          value: "{{ .Values.gitSync.repo }}"
        - name: GIT_SYNC_BRANCH
          value: "{{ .Values.gitSync.branch }}"
        - name: GIT_SYNC_ROOT
          value: "{{ .Values.gitSync.root }}"
        - name: GIT_SYNC_WAIT
          value: "{{ .Values.gitSync.wait | quote }}"
        - name: GIT_SYNC_ONE_TIME
          value: "{{ .Values.gitSync.oneTime | quote }}"
        - name: GIT_SYNC_SUBPATH
          value: "dags"
      args:
        - "--repo={{ .Values.gitSync.repo }}"
        - "--branch={{ .Values.gitSync.branch }}"
        - "--root={{ .Values.gitSync.root }}"
        - "--wait={{ .Values.gitSync.wait }}"
        - "--subpath=dags"
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
  volumes:
    - name: dags
      emptyDir: {}
