apiVersion: v1
kind: Pod
metadata:
  name: airflow-task-pod
spec:
  containers:
    - name: base
      image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      env:
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /opt/airflow/dags/repo/dags
    - name: git-sync
      image: k8s.gcr.io/git-sync/git-sync:v3.6.6
      args:
        - "--repo={{ .Values.dags.gitSync.repo }}"
        - "--branch={{ .Values.dags.gitSync.branch }}"
        - "--rev={{ .Values.dags.gitSync.rev }}"
        - "--root={{ .Values.dags.gitSync.root }}"
        - "--dest={{ .Values.dags.gitSync.dest }}"
        - "--wait={{ .Values.dags.gitSync.wait }}"
      volumeMounts:
        - name: dags
          mountPath: {{ .Values.dags.gitSync.mountPath }}
  volumes:
    - name: dags
      emptyDir: {}
