apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker-pod-template
  labels:
    app: airflow-worker
spec:
  restartPolicy: Never
  containers:
    - name: base
      image: "apache/airflow:2.7.1-python3.9"
      imagePullPolicy: IfNotPresent
      command: ["airflow", "tasks", "run"]
      env:
        - name: AIRFLOW_IS_K8S_EXECUTOR_POD
          value: "True"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags/repo/dags"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflowpassword@postgres-postgresql.airflow.svc.cluster.local:5432/airflow_db
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "bXKd_nJ7Yj0E309u7oh-cmXcFC89gi1IllSBl21Ku5g="
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: "Td_-CejX_6foYTgUzLXfrgVWvxlAuzp4Cemjf6J57b0"
      volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
          readOnly: true

    - name: git-sync
      image: k8s.gcr.io/git-sync/git-sync:v3.6.9
      imagePullPolicy: IfNotPresent
      env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/sserkanguzel/Project-1-Batch-Processing.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/git"
        - name: GIT_SYNC_DEST
          value: "repo"
        - name: GIT_SYNC_WAIT
          value: "60"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      volumeMounts:
        - name: dags-volume
          mountPath: /git

  volumes:
    - name: dags-volume
      emptyDir: {}
