apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-k8s-executor-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "watch"]
