apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-k8s-executor-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.airflow.serviceAccountName }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: airflow-k8s-executor-role
  apiGroup: rbac.authorization.k8s.io
