apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: {{ .Values.airflow.serviceAccountName }}
      containers:
      - name: scheduler
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            until pg_isready -h postgres-postgresql.{{ .Values.namespace }}.svc.cluster.local -p {{ .Values.database.postgres.port }}; do
              echo "Waiting for Postgres to be ready...";
              sleep 5;
            done;
            airflow db migrate && \
            exec airflow scheduler
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor }}
        - name: AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE
          value: {{ .Values.namespace }}
        - name: AIRFLOW__CORE__FERNET_KEY
          value: {{ .Values.airflow.fernetKey }}
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://{{ .Values.database.postgres.user }}:{{ .Values.database.postgres.password }}@postgres-postgresql.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.database.postgres.port }}/{{ .Values.database.postgres.db }}
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /opt/airflow/dags/repo/dags
        - name: AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE
          value: /opt/airflow/pod-template.yaml
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: pod-template-volume
          mountPath: /opt/airflow/pod-template.yaml
          subPath: pod-template.yaml
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.6
        args:
          - "--repo={{ .Values.dags.gitSync.repo }}"
          - "--branch={{ .Values.dags.gitSync.branch }}"
          - "--rev={{ .Values.dags.gitSync.rev }}"
          - "--root={{ .Values.dags.gitSync.mountPath }}"
          - "--dest={{ .Values.dags.gitSync.dest }}"
          - "--wait={{ .Values.dags.gitSync.wait }}"
        volumeMounts:
          - name: dags
            mountPath: {{ .Values.dags.gitSync.mountPath }}
      volumes:
      - name: dags
        emptyDir: {}
      - name: pod-template-volume
        configMap:
          name: airflow-pod-template
          items:
          - key: pod-template.yaml
            path: pod-template.yaml
