apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler # Corrected name
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler # Corrected label
  template:
    metadata:
      labels:
        app: airflow-scheduler # Corrected label
    spec:
      serviceAccountName: {{ .Values.airflow.serviceAccountName }}
      initContainers:
      - name: git-sync
        image: "{{ .Values.airflow.gitsync.image.repository }}:{{ .Values.airflow.gitsync.image.tag }}"
        env:
        - name: GIT_SYNC_REPO
          value: "{{ .Values.airflow.gitsync.repo }}"
        - name: GIT_SYNC_BRANCH
          value: "{{ .Values.airflow.gitsync.branch }}"
        - name: GIT_SYNC_DEST
          value: "dags" # This should match the path inside your repository where DAGs are.
        - name: GIT_SYNC_ONE_TIME
          value: "true" # Set to "false" for continuous sync by default with Argo CD. If you only want a one-time clone on pod start, set to "true".
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
      containers:
      - name: scheduler # Corrected container name
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            until pg_isready -h postgres-postgresql.airflow.svc.cluster.local -p 5432; do
                echo "Waiting for Postgres to be ready...";
                sleep 5;
            done;
            exec airflow scheduler # Corrected command
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor }}
        - name: AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE
          value: {{ .Values.namespace }}
        - name: AIRFLOW__CORE__FERNET_KEY
          value: {{ .Values.airflow.fernetKey }}
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: {{ .Values.airflow.secretKey }} # This might not be strictly needed for scheduler, but keeping it consistent
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://{{ .Values.database.postgres.user }}:{{ .Values.database.postgres.password }}@postgres-postgresql.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.database.postgres.port }}/{{ .Values.database.postgres.db }}
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags # This is where Airflow expects to find DAGs
      volumes:
      - name: dags-volume
        emptyDir: {}
