apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      serviceAccountName: {{ .Values.airflow.serviceAccountName }}
      containers:
      - name: webserver
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            until pg_isready -h postgres-postgresql.airflow.svc.cluster.local -p 5432; do
                echo "Waiting for Postgres to be ready...";
                sleep 5;
            done;
            airflow db migrate
            airflow users create \
              --username admin \
              --password admin \
              --firstname Airflow \
              --lastname Admin \
              --role Admin \
              --email admin@example.com || true
            exec airflow webserver
        ports:
        - containerPort: 8080
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor }}
        - name: AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE
          value: {{ .Values.namespace }}
        - name: AIRFLOW__CORE__FERNET_KEY
          value: {{ .Values.airflow.fernetKey }}
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: {{ .Values.airflow.secretKey }}
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://{{ .Values.database.postgres.user }}:{{ .Values.database.postgres.password }}@postgres-postgresql.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.database.postgres.port }}/{{ .Values.database.postgres.db }}
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      - name: git-sync
        image: "{{ .Values.gitSync.image.repository }}:{{ .Values.gitSync.image.tag }}"
        env:
        - name: GIT_SYNC_REPO
          value: "{{ .Values.gitSync.repo }}"
        - name: GIT_SYNC_BRANCH
          value: "{{ .Values.gitSync.branch }}"
        - name: GIT_SYNC_ROOT
          value: "{{ .Values.gitSync.root }}"
        - name: GIT_SYNC_WAIT
          value: "{{ .Values.gitSync.wait | quote }}"
        args:
        - "--repo={{ .Values.gitSync.repo }}"
        - "--branch={{ .Values.gitSync.branch }}"
        - "--root={{ .Values.gitSync.root }}"
        - "--wait={{ .Values.gitSync.wait }}"
        volumeMounts:
        - name: dags
          mountPath: "{{ .Values.gitSync.volumeMountPath }}"
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.webserver.type }}
  ports:
  - port: {{ .Values.service.webserver.port }}
    targetPort: 8080
  selector:
    app: airflow-webserver
