apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-standalone
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-standalone
  template:
    metadata:
      labels:
        app: airflow-standalone
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.9.1
        command: ["airflow"]
        args: ["standalone"]
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-standalone
  namespace: airflow
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: airflow-standalone
