apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: apache/hive:3.1.3
          ports:
            - containerPort: 9083
          env:
            - name: SERVICE_NAME
              value: metastore
            - name: DB_TYPE
              value: postgres
            - name: HIVE_DB
              valueFrom:
                configMapKeyRef:
                  name: hive-config
                  key: dbName
            - name: HIVE_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: hive-config
                  key: dbUser
            - name: HIVE_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hive-config
                  key: dbPassword
            - name: HIVE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: hive-config
                  key: dbHost
            - name: HIVE_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: hive-config
                  key: dbPort
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
  type: ClusterIP
