apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Release.Namespace }}
data:
  vault-config.hcl: |
    storage "file" {
      path = "/vault/file"
    }
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    ui = true
    disable_mlock = true
