minio:
  image:
    repository: minio/minio
    tag: RELEASE.2025-06-13T11-33-47Z-cpuv1
    pullPolicy: IfNotPresent

  rootuser: minioadmin
  rootpassword: minioadmin

  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path

  service:
    type: NodePort
    nodePort: 30090

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
