namespace: airflow

airflow:
  image:
    repository: apache/airflow
    tag: 2.7.1-python3.9
  executor: KubernetesExecutor
  fernetKey: "bXKd_nJ7Yj0E309u7oh-cmXcFC89gi1IllSBl21Ku5g="
  secretKey: "Td_-CejX_6foYTgUzLXfrgVWvxlAuzp4Cemjf6J57b0"
  serviceAccountName: airflow
  initDbJob:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/sserkanguzel/Project-1-Batch-Processing.git
    branch: main
    rev: HEAD
    depth: 1
    wait: 60
    subPath: dags
    image:
      repository: registry.k8s.io/git-sync/git-sync
      tag: v3.6.9

database:
  postgres:
    user: airflow
    password: airflowpassword
    db: airflow_db
    port: 5432

service:
  webserver:
    type: NodePort
    port: 8080
