namespace: airflow

airflow:
  image:
    repository: apache/airflow
    tag: 2.7.1-python3.9
  executor: KubernetesExecutor
  fernetKey: "bXKd_nJ7Yj0E309u7oh-cmXcFC89gi1IllSBl21Ku5g="     # generate with python cryptography (see below)
  secretKey: "Td_-CejX_6foYTgUzLXfrgVWvxlAuzp4Cemjf6J57b0"     # random string for webserver session
  serviceAccountName: airflow
  initDbJob: # Set to false after inital setup
    enabled: false

database:
  postgres:
    user: airflow
    password: airflowpassword
    db: airflow_db
    port: 5432

service:
  webserver:
    type: NodePort
    port: 8080

dags:
  gitSync:
    repo: https://github.com/sserkanguzel/Project-1-Batch-Processing.git
    branch: main
    rev: HEAD
    root: /git
    dest: repo
    wait: 60
    mountPath: /opt/airflow/dags

kubernetesExecutor:
  podTemplate:
    enabled: true
    path: templates/pod-template.yaml
