namespace: airflow

airflow:
  image:
    repository: apache/airflow
    tag: 2.7.1-python3.9

  executor: KubernetesExecutor

  kubernetesExecutor:
    workerContainerImage: "apache/airflow:2.7.1-python3.9"
    podTemplate:
      configMapName: airflow-pod-template
      name: pod_template.yaml

  fernetKey: "bXKd_nJ7Yj0E309u7oh-cmXcFC89gi1IllSBl21Ku5g="     # generate with python cryptography
  secretKey: "Td_-CejX_6foYTgUzLXfrgVWvxlAuzp4Cemjf6J57b0"      # random string for webserver session

  serviceAccountName: airflow

  initDbJob:
    enabled: false

  # Git Sync configuration for DAGs
  gitsync:
    image:
      repository: k8s.gcr.io/git-sync/git-sync
      tag: v3.6.9
    repo: "https://github.com/sserkanguzel/Project-1-Batch-Processing.git"
    branch: "main"
    subPath: dags

  # Logging configuration
  config:
    logging:
      base_log_folder: /opt/airflow/logs
      remote_logging: "False"

  logs:
    persistence:
      enabled: true
      existingClaim: airflow-logs-pvc
      mountPath: /opt/airflow/logs

database:
  postgres:
    user: airflow
    password: airflowpassword
    db: airflow_db
    port: 5432

service:
  webserver:
    type: NodePort
    port: 8080
