apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: bde2020/hive:2.3.2-postgresql-metastore
          ports:
            - containerPort: 9083
          env:
            - name: HIVE_SITE_CONF_fs_defaultFS
              value: "s3a://testbuckettrino"
            - name: HIVE_SITE_CONF_fs_s3a_endpoint
              value: "http://minio.minio.svc.cluster.local:30091"
            - name: HIVE_SITE_CONF_fs_s3a_access.key
              value: "minioadmin"
            - name: HIVE_SITE_CONF_fs_s3a_secret.key
              value: "minioadmin"
            - name: HIVE_SITE_CONF_fs_s3a_path.style.access
              value: "true"
            - name: HIVE_SITE_CONF_fs_s3a_connection_ssl_enabled
              value: "false"
            - name: HIVE_SITE_CONF_hive.metastore.warehouse.dir
              value: "s3a://testbuckettrino/testpathtrino"
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  type: ClusterIP
  selector:
    app: hive-metastore
  ports:
    - port: 9083
      targetPort: 9083
