apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: bde2020/hive-metastore-postgresql:3.1.0
          ports:
            - containerPort: 9083
          env:
            - name: HIVE_METASTORE_DB_TYPE
              value: "postgres"
            - name: HIVE_METASTORE_USER
              value: "metastore"
            - name: HIVE_METASTORE_PASSWORD
              value: "mypassword"
            - name: HIVE_METASTORE_DATABASE_NAME
              value: "metastore"
            - name: HIVE_METASTORE_DATABASE_HOST
              value: "postgresql.postgresql.svc.cluster.local"
            - name: HIVE_METASTORE_DATABASE_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  type: ClusterIP
  selector:
    app: hive-metastore
  ports:
    - port: 9083
      targetPort: 9083
