apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      volumes:
        - name: hive-extra-libs
          emptyDir: {}

      initContainers:
        - name: download-s3-jars
          image: bitnami/minideb
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && apt-get install -y wget ca-certificates
              wget -P /shared https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.4/hadoop-aws-2.7.4.jar
              wget -P /shared https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.271/aws-java-sdk-bundle-1.11.271.jar
          volumeMounts:
            - name: hive-extra-libs
              mountPath: /shared

      containers:
        - name: hive-metastore
          image: your-hive-image:tag  # Replace with your Hive image
          ports:
            - containerPort: 9083
          env:
            - name: HIVE_METASTORE_USER
              value: "admin"
            - name: HIVE_METASTORE_DB
              value: "hive_metastore"
            - name: HIVE_METASTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: your-postgres-secret
                  key: password
            - name: HIVE_METASTORE_URI
              value: "jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/hive_metastore"
          volumeMounts:
            - name: hive-extra-libs
              mountPath: /opt/hive/lib


---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: {{ .Values.service.port }}
      targetPort: 9083

