apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      # Volumes shared between init and main container
      volumes:
        - name: hive-extra-libs
          emptyDir: {}  # Temporary volume to hold JARs
        - name: hive-config
          configMap:
            name: hive-site-config  # Must already exist

      initContainers:
        - name: setup-hive
          image: apache/hive:3.1.3
          command:
            - /bin/bash
            - -c
            - |
              echo "[INFO] Downloading required JARs..."
              mkdir -p /opt/hive/lib
              wget -P /opt/hive/lib https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.4/hadoop-aws-2.7.4.jar
              wget -P /opt/hive/lib https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.271/aws-java-sdk-bundle-1.11.271.jar
              echo "[INFO] Running Hive schema initialization..."
              schematool -dbType postgres -initSchema --verbose
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          volumeMounts:
            - name: hive-extra-libs
              mountPath: /opt/hive/lib
            - name: hive-config
              mountPath: /opt/hive/conf

      containers:
        - name: hive-metastore
          image: apache/hive:3.1.3  # Replace if using a custom image
          ports:
            - containerPort: 9083
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          volumeMounts:
            - name: hive-extra-libs
              mountPath: /opt/hive/lib
            - name: hive-config
              mountPath: /opt/hive/conf

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive
spec:
  type: ClusterIP  # Adjust to NodePort/LoadBalancer if needed
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
