apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: "{{ .Values.hive.image.repository }}:{{ .Values.hive.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: HIVE_METASTORE_DB_TYPE
              value: "postgres"
            - name: HIVE_METASTORE_USER
              value: "{{ .Values.hive.database.user }}"
            - name: HIVE_METASTORE_PASSWORD
              value: "{{ .Values.hive.database.password }}"
            - name: HIVE_METASTORE_DATABASE_NAME
              value: "{{ .Values.hive.database.name }}"
            - name: HIVE_METASTORE_DATABASE_HOST
              value: "{{ .Values.hive.database.host }}"
            - name: HIVE_METASTORE_DATABASE_PORT
              value: "{{ .Values.hive.database.port}}"
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hive-metastore
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
