apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: bde2020/hive:2.3.2-postgresql-metastore
          ports:
            - containerPort: 9083
          env:
            - name: HIVE_SITE_CONF_fs_defaultFS
              value: s3a://testbuckettrino
            - name: HIVE_SITE_CONF_fs_s3a_endpoint
              value: http://minio.minio.svc.cluster.local:9000
            - name: HIVE_SITE_CONF_fs_s3a_access_key
              value: minioadmin
            - name: HIVE_SITE_CONF_fs_s3a_secret_key
              value: minioadmin
            - name: HIVE_SITE_CONF_fs_s3a_path_style_access
              value: "true"
            - name: HIVE_SITE_CONF_fs_s3a_connection_ssl_enabled
              value: "false"
            - name: HIVE_SITE_CONF_hive_metastore_warehouse_dir
              value: s3a://testbuckettrino/testpathtrino
          volumeMounts:
            - name: hive-site-config
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
      volumes:
        - name: hive-site-config
          configMap:
            name: hive-site-config
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive-metastore
spec:
  type: ClusterIP
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
