apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: bde2020/hive:2.3.2-postgresql-metastore
          command: ["/opt/hive/bin/hive"]
          args: ["--service", "metastore"]
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: hive-site
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
      volumes:
        - name: hive-site
          configMap:
            name: hive-site-config

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: {{ .Values.service.port }}
      targetPort: 9083

