apiVersion: batch/v1
kind: Job
metadata:
  name: hive-metastore-init
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-schema
          image: apache/hive:2.3.2
          command:
            - /bin/bash
            - -c
            - >
              schematool -dbType postgres -initSchema --verbose
          env:
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf
      volumes:
        - name: hive-config
          configMap:
            name: hive-site-config  # assuming your hive-site.xml is in a ConfigMap
